### ISSUE TITLE
Model is invisible when loaded inside Roblox Studio

### ISSUE THREAD

**Issue by shadow01148** [CloneTrooper1019/Source2Roblox#1]
Did I do anything wrong?

**Comment by CloneTrooper1019** [comment]
Are you using my mod manager? The files aren’t deployed to regular versions of Roblox Studio, it targets a specific build folder that my mod manager uses.

**Comment by CloneTrooper1019** [comment]
(Specifically, `%localappdata%\Roblox Studio\content` is the folder it’ll be writing local files to.

**Comment by shadow01148** [comment]
It worked when I used your mod manager. Thanks!
