### ISSUE TITLE
Cannot build nor debug - metadata file missing & nuget packages broken

### ISSUE THREAD

**Issue by Marimariius** [CloneTrooper1019/Source2Roblox#11]
**Error List:**
 ![image](https://user-images.githubusercontent.com/55176902/133516457-68570393-5748-4e6d-8dc2-e82bb981a953.png)
**Output:**
![image](https://user-images.githubusercontent.com/55176902/133516500-96982995-82ba-4c71-8f98-06ba7ba0e5d2.png)

They're probably useless but I don't know what else can help

**Comment by shadow01148** [comment]
Put RobloxFileFormat.dll (Located on Roblox-File-Format folder) to ./bin/Debug

**Comment by Marimariius** [comment]
thanks for the help @shadow01148! it works properly now (aside from it not being able to display any of the textures in normal studio), i'll close the issue now

**Comment by rxya-l** [comment]
Im having this exact issue with the nuget packages yet the solution does not work, any help?
