### ISSUE TITLE
MeshBuilder.cs error 

### ISSUE THREAD

**Issue by shadow01148** [CloneTrooper1019/Source2Roblox#2]
![image](https://user-images.githubusercontent.com/76457846/131591596-a7c4fa13-881f-4605-b282-498fcddd6b83.png)

**Comment by CloneTrooper1019** [comment]
Do you have Roblox-File-Format forked? Not sure what’s going on there.

**Comment by shadow01148** [comment]
Yes, I have it forked

**Comment by shadow01148** [comment]
Managed to make it work but I had to use an older version of this repo.

**Comment by shadow01148** [comment]
I accidentally made the current version work. I guess this is solved???

**Comment by thefiretheyou** [comment]
how

**Comment by shadow01148** [comment]
> how

I reinstalled Roblox-File-Format and Source2Roblox
