### ISSUE TITLE
Will this be fixed in the future?

### ISSUE THREAD

**Issue by shadow01148** [CloneTrooper1019/Source2Roblox#9]
![image](https://user-images.githubusercontent.com/76457846/132276997-824d394a-19af-4021-90e8-0e26b2739d77.png)

I'm not sure if you see it.

**Comment by CloneTrooper1019** [comment]
Gonna look into ways I can minimize this effect, but it’s not trivial to fix unfortunately.

**Comment by shadow01148** [comment]
Thanks for your response.
